version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./frontend # path to dockerfile
    ports: # Port binding to host from docker container
      - "3377:8080" # Bind port 3377 of host to 8080 of container
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
      - SERVER_API_URL
    container_name: frontend-docker
    restart: always # What to do if container crashes
    depends_on:
      - backend
    networks:
      - transcendence
  # Create backend container
  backend:
    # Create backend container  
    build: ./backend
    expose:
      - BACKEND_PORT # Expose port 3370 to other containers
    ports:
      - ${BACKEND_PORT}:3370 # For debugging - Bind port 3370 of host to 3370 of container
      - "5555:5555" # For debugging - access to prisma studio
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - BACKEND_PORT
    container_name: backend-docker
    restart: always
    depends_on:
      - dev-db
    networks:
      - transcendence
  # Create database container
  dev-db:
    image: postgres:13
    container_name: ${POSTGRES_CONTAINER_NAME}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - transcendence
networks:
  transcendence: